# -*- coding: utf-8 -*-

{
    'name': "cap_sale",
    'summary': "Personnalisation du module Ventes (sale) pour EVEREST.",
    'description': "Création du devis à partir de projet / tâches.",
    'author': "Captivea",
    'website': "https://www.captivea.com",
    'category': 'Sales',
    'version': '17.0.1.1',  # Correction du format de version
    'depends': [
        'sale',
        'sales_team',
        'sale_project',
        'cap_project',
        'industry_fsm_sale',
        'cap_industry_fsm',
        'cap_contact',
        'cap_product',
        'uom',
        'product',
        'account',
        'cap_ref_models',
        'cap_account',
        'cap_security',
        'l10n_fr',
        'l10n_fr_invoice_addr',
        'web',
    ],
    'data': [
        'data/base_document_layout/ir_ui_view.xml',
        'data/sale_order/ir_ui_view.xml',
        'data/sale_order/ir_actions_server.xml',
        'data/account_move/ir_ui_view.xml',
        'data/account_move/ir_ui_menu.xml',
        'data/certificate_ee/ir_ui_view.xml',
        'data/certificate_ee/ir_model_access.xml',
        'data/certificate_ee/ir_rule.xml',
        'data/product_isolant_alternative/ir_ui_view.xml',
        'data/product_template/ir_ui_menu.xml',
        'data/res_config_settings/ir_ui_view.xml',
        'data/res_company/ir_ui_view.xml',
        'data/product_pricelist_item/ir_ui_view.xml',
        'data/project_task/ir_ui_view.xml',
        'data/project_task_zone/ir_ui_view.xml',
        'data/project_task_zone_order_wizard/ir_ui_view.xml',
        'data/project_task_zone_order_wizard/ir_model_access.xml',
        'data/type_travaux/ir_ui_view.xml',
        'report/external_layout.xml',
        'report/report_sale_order.xml',
        'report/invoice_report_template.xml',
        'report/report.xml',
        'data/wizard_force_date_order/ir_ui_view.xml',
        'data/wizard_force_date_order/ir_model_access.xml',
        'data/wizard_print_order/ir_ui_view.xml',
        'data/wizard_print_order/ir_model_access.xml',
    ],
    'qweb': [],
    'demo': [],
}
