{
    'name': "cap_project",
    'summary': "Personnalisation du module Projet pour EVEREST.",
    'description': "Ajout Secteurs d'activité.",
    'author': "Captivea",
    'website': "https://www.captivea.com",
    'category': 'Tools',  # La catégorie reste la même
    'version': '17.0.2.0.0',  # Mise à jour de la version pour Odoo 17
    'depends': [
        'project',
        'cap_contact',
        'industry_fsm',
        'documents',
        'documents_project',
        'fleet',
        'cap_ref_models',
        'mail',
        'cap_security',
    ],
    'data': [
        'data/destination_batiment/ir_ui_menu.xml',
        'data/destination_batiment/ir_model_access.xml',
        'data/documents_folder/documents_folder.xml',
        'data/documents_folder/ir_model_access.xml',
        'data/documents_facet/documents_facet.xml',
        'data/documents_tag/documents_tag.xml',
        'data/project/ir_ui_view.xml',
        'data/project_batiment/ir_model_access.xml',
        'data/project_batiment/ir_ui_view.xml',
        'data/project_batiment_entree/ir_model_access.xml',
        'data/project_batiment_entree/ir_ui_view.xml',
        'data/project_status/ir_model_access.xml',
        'data/project_status/ir_ui_view.xml',
        'data/project_status/data.xml',
        'data/project_task/ir_ui_view.xml',
        'data/project_task_zone/ir_ui_view.xml',
        'data/project_task_zone/ir_model_access.xml',
        'data/project_task_zone_type/ir_model_access.xml',
        'data/res_partner/ir_ui_view.xml',
        'data/res_config_settings/ir_ui_view.xml',
        # 'data/res_config_data.xml',
        'data/resistance_thermique/ir_ui_menu.xml',
        'data/resistance_thermique/ir_model_access.xml',
        'data/secteur_activite/ir_ui_menu.xml',
        'data/secteur_activite/ir_model_access.xml',
        'data/systeme_chauffage/ir_ui_menu.xml',
        'data/systeme_chauffage/ir_model_access.xml',
        'data/type_travaux/ir_ui_menu.xml',
        'data/type_travaux/ir_model_access.xml',
        'data/type_support/ir_ui_menu.xml',
        'data/type_support/ir_model_access.xml',
        'data/type_travaux_product_category/ir_ui_view.xml',
        'data/type_travaux_product_category/ir_model_access.xml',
        'data/zone_product_line/ir_model_access.xml',
    ],
    'qweb': [],
    'demo': [],
    'installable': True,  # Ajout pour permettre l'installation du module
}
